spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  session:
    store-type: none
#security:
#  basic:
#    enabled: false
weya:
  security:
    browser:
#      loginPage: /demo-sign.html
      loginPage: /demo-sign.html
      loginType: REDIRECT
      signUpUrl: /demo-signUp.html
#      filterProcessesUrl: /login/qq
    code:
      image:
#        length: 6
#        width: 100
        url: /user/*
    social:
      filterProcessesUrl: /login
      qq:
        app-id: 101386962
        app-secret: 2a0f820407df400b84a854d054be8b6a
        providerId: qq
      weixin:
        app-id: wxfd6965ab1fc6adb2
        app-secret: 66bb4566de776ac699ec1dbed0cc3dd1
server:
  port: 80
